# Generated by Django 5.1.1 on 2024-09-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=75)),
                ('password', models.CharField(default='', max_length=75)),
                ('email', models.CharField(default='', max_length=75)),
                ('village', models.CharField(default='', max_length=75)),
                ('taluka', models.CharField(default='', max_length=75)),
                ('district', models.CharField(default='', max_length=75)),
                ('phone_no', models.IntegerField(null=True)),
                ('post', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
