# Generated by Django 5.1.1 on 2024-09-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_equipment_userdetails_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=75)),
                ('customer_id', models.IntegerField(null=True)),
                ('customer_village', models.CharField(default='', max_length=75)),
                ('customer_taluka', models.CharField(default='', max_length=75)),
                ('customer_district', models.CharField(default='', max_length=75)),
                ('customer_phone', models.CharField(default='', max_length=75)),
                ('equipment_name', models.CharField(default='', max_length=75)),
                ('equipment_id', models.IntegerField(null=True)),
                ('equipmentholder_phone_no', models.IntegerField(null=True)),
                ('equipmentholder_id', models.IntegerField(null=True)),
                ('equipmentholder_name', models.CharField(default='', max_length=75)),
                ('equipmentholder_village', models.CharField(default='', max_length=75)),
                ('equipmentholder_taluka', models.CharField(default='', max_length=75)),
                ('equipmentholder_district', models.CharField(default='', max_length=75)),
                ('rent', models.IntegerField(null=True)),
                ('take_date', models.CharField(default='', max_length=75)),
                ('give_date', models.CharField(default='', max_length=75)),
                ('total_rent', models.IntegerField(null=True)),
                ('request_status', models.CharField(default='Pending', max_length=75)),
            ],
        ),
    ]
